pull_request_rules:
  - name: Manual-Merge label when Auto-Reviewed
    conditions:
      - status-success=auto-review
    actions:
      label:
        add:
          - manual-merge
      comment:
        message: This Pull request has been auto-reviewed and is ready for manual merge.
  - name: Automatic merge
    description: Merge when PR passes all status checks and has been reviewed
    conditions:
      - status-success=build
      - status-success=run
      - approved-reviews-by>=1
      - check-success=codecov/patch
      - check-success=codecov/project
      - label != manual-merge
    actions:
      merge:
        method: merge
        commit_message_template: |
          Merge: {{ title.strip() }}
