pull_request_rules:
  - name: Automatic merge
    description: Merge when PR passes all status checks and has been reviewed
    conditions:
      - status-success=evaluate-code-coverage
      - status-success=run-all-tests
      - status-success=build-nextjs-application
      - approved-reviews-by>=1
      - check-success=codecov/patch
      - check-success=codecov/project
      - -approved-reviews-by=harvey-specter # require manual-merge when auto-approved
    actions:
      merge:
        method: merge
        commit_message_template: >
          Merge: {{ title.strip() }}
      comment:
        message: This Pull request satisfies all status-checks and will be automatically merged soon.

  - name: Manual merge when Auto-Reviewed
    conditions:
      - approved-reviews-by=harvey-specter
    actions:
      label:
        add:
          - "manual-merge"
      comment:
        message: This Pull request has been auto-reviewed and is ready for manual merge.