pull_request_rules:
  - name: Wrong Pull Request Base
    conditions:
      - base=main
      - -head=canary
    actions:
      comment:
        message: "@{{ author }} The base of the Pull request cannot be set to `main`. Please use `canary` instead."

  - name: Automatically Merge Pull Requests into Canary
    description: Merges a PR once all status-checks pass and once it has been reviewed by at least one person
    conditions:
      - status-success=evaluate-code-coverage
      - status-success=run-all-tests
      - status-success=build-nextjs-application
      - approved-reviews-by>=1
      - check-success=codecov/patch
      - check-success=codecov/project
      - -label=manual-merge # do not auto merge when manual-merge label is present
      - -approved-reviews-by=Harvey-Reginald-Specter # require manual-merge when auto-approved
      - base=canary
    actions:
      comment:
        message: This Pull request satisfies all status-checks and will be automatically merged soon.
      merge:
        method: merge
        commit_message_template: >
          Merge: {{ title.strip() }}

  - name: Automatically Merge Pull Requests from Canary into Main
    description: Merges Changes from Canary into Main once all status checks have passed and marked as done
    conditions:
      - status-success=evaluate-code-coverage
      - status-success=run-all-tests
      - status-success=build-nextjs-application
      - check-success=codecov/patch
      - check-success=codecov/project
      - label=done # only merge once marked as done
      - base=main
    actions:
      comment:
        message: This Pull request satisfies all status-checks and will be automatically merged soon.
      merge:
        method: merge

  - name: Notify about Missing Done Label
    description: A Pull Request that is to be merged into the main branch must be marked as done to be merged. Notify authors about missing label, when all checks pass.
    conditions:
      - status-success=evaluate-code-coverage
      - status-success=run-all-tests
      - status-success=build-nextjs-application
      - check-success=codecov/patch
      - check-success=codecov/project
      - -label=done
      - base=main
      - head=canary
    actions:
      comment:
        message: Keep in mind, that this Pull request is only merged once it is marked as done!


  - name: Add 'Manual-Merge' label to PR when Auto-Reviewed
    conditions:
      - approved-reviews-by=Harvey-Reginald-Specter
      - -label=manual-merge
    actions:
      label:
        add:
          - "manual-merge"
      comment:
        message: This Pull request has been auto-reviewed and is ready for manual merge.

  - name: Auto-Assign Marty-Byrde as Reviewer when Status Checks Pass and Marty-Byrde is not the Author
    conditions:
      - status-success=evaluate-code-coverage
      - status-success=run-all-tests
      - status-success=build-nextjs-application
      - -approved-reviews-by>=1
      - check-success=codecov/patch
      - check-success=codecov/project
      - -approved-reviews-by=Harvey-Reginald-Specter
      - -author=Marty-Byrde
      - -review-requested=Marty-Byrde # has not been requested for review
      - base=canary
    actions:
      request_reviews:
        users:
          - "Marty-Byrde"
      comment:
        message: "Auto-Assigned Marty-Byrde as a Reviewer to this Pull Request."

  - name: Auto-Assign MrsicMarko as Reviewer when Status Checks Pass and MrsicMarko is not the Author
    conditions:
      - status-success=evaluate-code-coverage
      - status-success=run-all-tests
      - status-success=build-nextjs-application
      - -approved-reviews-by>=1
      - check-success=codecov/patch
      - check-success=codecov/project
      - -approved-reviews-by=Harvey-Reginald-Specter
      - -author=MrsicMarko
      - -review-requested=MrsicMarko # has not been requested for review
      - base=canary
    actions:
      request_reviews:
        users:
          - "MrsicMarko"
      comment:
        message: "Auto-Assigned MrsicMarko as a Reviewer to this Pull Request."

  - name: Automatic Update-Branch when Canary is ahead
    conditions:
      - base = canary
      - "#commits-behind > 0"
    actions:
      update:
      comment:
        message: "@{{ author }} This Pull request has been automatically updated, because the canary branch was ahead."


