name: Automatically Create Pull Request for Canary Branch (using Marty-Byrde PAT)

on:
  push:
    branches:
      - canary

jobs:
  auto-create-pull-request-for-canary:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN_SEMANTIC_VERSIONING }}

    steps:
      - uses: actions/checkout@v3

      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"


      - name: Get Latest Hash
        run: |
            LATEST_HASH=$(git rev-parse --short HEAD)
            echo "LATEST_HASH=$LATEST_HASH" >> $GITHUB_ENV

      - name: Create pull request
        id: open-pr
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          pr_title: "Merge Changes into Main from Canary (${{ steps.previoustag.outputs.tag }}-${{ env.LATEST_HASH }})"
          pr_draft: false