name: Auto PR Review

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - uses: omio-labs/pr-reviewer-bot@v1
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN_AUTO_REVIEW }}

      - name: Approve Pull request if only allowed files were changed
        if: success()  # Ensure this runs only if the previous step succeeds
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.ACCESS_TOKEN_AUTO_REVIEW }}
          script: |
            await github.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              event: 'APPROVE',
              body: 'Auto-approved because only allowed files were changed.'
            });