name: Build and Push Docker Image

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    env:
      IMAGE_URI: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        run: |
          docker build -t $IMAGE_URI:latest .

      - name: Push the image
        run: |
          docker push $IMAGE_URI:latest
