name: Build NextJS Application

#on: push

jobs:
  build-nextjs-application:
    runs-on: ubuntu-latest
    env:
      NEXT_AUTH_GITHUB_ID: ${{ secrets.NEXT_AUTH_GITHUB_ID }}
      NEXT_AUTH_GITHUB_SECRET: ${{ secrets.NEXT_AUTH_GITHUB_SECRET }}
      NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node 21
        uses: actions/setup-node@v3
        with:
          node-version: 21

      - name: Install dependencies
        run: yarn

      - name: Run Linting
        run: npm run lint

      - name: Run Build-Script
        run: npm run build