name: Continuous Integration Pipeline
on: push

permissions:
  contents: read
  checks: write
  statuses: write

jobs:
  run:
    runs-on: ubuntu-latest

    # Pass along the environment variables
    environment: Env Variables

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node 21
        uses: actions/setup-node@v3
        with:
          node-version: 21

      - name: Install dependencies
        run: yarn

      - name: Run Jest Tests and Collect Coverage
        run: npm run jest:test

      - name: Upload Coverage to Codecov
        if: ${{ !env.ACT }} # Do not run locally
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: /coverage/**/lcov.info
#          flags: unittests
          fail_ci_if_error: true
          verbose: true
