name: Run Tests
on: push
jobs:

  # Build Job
  build:
    runs-on: ubuntu-latest
    # Pass along the environment variables
    environment: Env Variables

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install Dependencies
        run: yarn install

      - name: Install Playwright Browsers
        run: npx playwright install

      - name: Run Playwright Tests
        run: npm run test

      - name: Run Jest Tests
        run: npm run jest:test
